//Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

let fibonacciArr = [1, 2],
    sum = 0,
    nextTerm = 0,
    limit = 4000000;

while ((fibonacciArr[fibonacciArr.length - 1] + fibonacciArr[fibonacciArr.length - 2]) <= limit) {
  nextTerm = fibonacciArr[fibonacciArr.length - 1] + fibonacciArr[fibonacciArr.length - 2];
  sum += nextTerm % 2 === 0 ? nextTerm : 0;

  fibonacciArr.push(nextTerm);
}

console.log(sum);
